version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # Порт для доступа к управлению RabbitMQ
      - "5672:5672"   # Основной порт RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  producer:
    build: ./producer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
